### ISSUE TITLE
Content not being pulled in correctly

### ISSUE THREAD

**Issue by sachajudd** [silverstripe/userhelp.silverstripe.org#79]
The RefreshMarkdown task isn't working the way it should and the content is not being pulled in from https://github.com/silverstripe/silverstripe-userhelp-content https://github.com/silverstripe/userhelp.silverstripe.org/blob/master/app/_config/docs-repositories.yml correctly. If @silverstripe/creative-commoners could step in and make sure the errors are being handled properly and it logs them correctly that would be great. Could someone also look into the DocumentationManifest.php for some clues. This is where the error comes from: https://github.com/silverstripe/silverstripe-docsviewer/blob/master/code/DocumentationManifest.php#L138

**Comment by sachajudd** [comment]
You can see here the optional features aren't all getting pulled in.

![image](https://user-images.githubusercontent.com/24258161/55198869-a8703a80-521c-11e9-8b75-0e245abe5101.png)

The site is very temperamental and has had content and then no content about 3 times in the last few hours.

**Comment by brynwhyman** [comment]
It would be worth merging this at the same time https://github.com/silverstripe/userhelp.silverstripe.org/pull/78

**Comment by brynwhyman** [comment]
Please reindex the search too

**Comment by robbieaverill** [comment]
>Could someone also look into the DocumentationManifest.php for some clues. This is where the error comes from: https://github.com/silverstripe/silverstripe-docsviewer/blob/master/code/DocumentationManifest.php#L138

This line of code is correctly identifying that the documentation folder doesn't exist. The RefreshMarkdownTask is in charge of creating these folders, so when DocumentationManifest is run (when viewing a page or via DocumentationBuild) it should exist.

>make sure the errors are being handled properly and it logs them correctly

At this point this error is valid. There's nothing else it can do except for fail. Errors are currently available in Graylog (e.g. https://logs.platform.silverstripe.com/messages/graylog_1112/8c981a72-519b-11e9-b7ce-064e5e2710d6).

I will add Raygun as well.

We run the same code as this for docs.silverstripe.org and cwp.govt.nz - the problem doesn't occur there. I suspect this has happened because I deleted some userforms branches (removed in this repo with 343fa0b9e85aa685b7ab8a47217384b8390a0781), which would've broken the RefreshMarkdownTask and may have left the source markdown files in a broken state. Potentially at this point some manual intervention on the server may have removed the files, or made them unreadable.

@cheddam has added queuedjobs to the project, so we can run the RefreshMarkdownTask via a job instead of via the browser (the "trick" is to run the task and close the tab, allowing it to complete in the background).

I've manually run the RefreshMarkdownTask and DocumentationBuild tasks, both completed successfully, and smoke testing content on the frontend looks like it's all there.

Follow up actions:

* Deploy queuedjobs
* Add Raygun integration

@sachajudd you may also want to uncomment your cron task so it will run nightly again

**Comment by robbieaverill** [comment]
Also tested on UAT, seems OK =)

**Comment by sachajudd** [comment]
Cheers, I'll uncomment on Monday incase something happens over the weekend 🙂
